# Google Cloud Build configuration for building and deploying the application
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tenders-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tenders-backend:latest'
      - '.'
    id: 'build-image'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/tenders-backend:$COMMIT_SHA'
    id: 'push-image-sha'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/tenders-backend:latest'
    id: 'push-image-latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'tenders-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tenders-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=3000'
      - '--set-secrets'
      - 'MONGODB_URI=mongodb-uri:latest,JWT_SECRET=jwt-secret:latest'
    id: 'deploy-cloudrun'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/tenders-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/tenders-backend:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build timeout
timeout: '1200s'